// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	entity "book-lending-api/internal/borrow/entity"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// IBorrowRepository is an autogenerated mock type for the IBorrowRepository type
type IBorrowRepository struct {
	mock.Mock
}

type IBorrowRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *IBorrowRepository) EXPECT() *IBorrowRepository_Expecter {
	return &IBorrowRepository_Expecter{mock: &_m.Mock}
}

// CreateBorrowing provides a mock function with given fields: ctx, b
func (_m *IBorrowRepository) CreateBorrowing(ctx context.Context, b *entity.Borrowing) error {
	ret := _m.Called(ctx, b)

	if len(ret) == 0 {
		panic("no return value specified for CreateBorrowing")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Borrowing) error); ok {
		r0 = rf(ctx, b)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IBorrowRepository_CreateBorrowing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBorrowing'
type IBorrowRepository_CreateBorrowing_Call struct {
	*mock.Call
}

// CreateBorrowing is a helper method to define mock.On call
//   - ctx context.Context
//   - b *entity.Borrowing
func (_e *IBorrowRepository_Expecter) CreateBorrowing(ctx interface{}, b interface{}) *IBorrowRepository_CreateBorrowing_Call {
	return &IBorrowRepository_CreateBorrowing_Call{Call: _e.mock.On("CreateBorrowing", ctx, b)}
}

func (_c *IBorrowRepository_CreateBorrowing_Call) Run(run func(ctx context.Context, b *entity.Borrowing)) *IBorrowRepository_CreateBorrowing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Borrowing))
	})
	return _c
}

func (_c *IBorrowRepository_CreateBorrowing_Call) Return(_a0 error) *IBorrowRepository_CreateBorrowing_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IBorrowRepository_CreateBorrowing_Call) RunAndReturn(run func(context.Context, *entity.Borrowing) error) *IBorrowRepository_CreateBorrowing_Call {
	_c.Call.Return(run)
	return _c
}

// GetBorrowingByID provides a mock function with given fields: ctx, id
func (_m *IBorrowRepository) GetBorrowingByID(ctx context.Context, id int64) (*entity.Borrowing, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetBorrowingByID")
	}

	var r0 *entity.Borrowing
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*entity.Borrowing, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *entity.Borrowing); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Borrowing)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IBorrowRepository_GetBorrowingByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBorrowingByID'
type IBorrowRepository_GetBorrowingByID_Call struct {
	*mock.Call
}

// GetBorrowingByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *IBorrowRepository_Expecter) GetBorrowingByID(ctx interface{}, id interface{}) *IBorrowRepository_GetBorrowingByID_Call {
	return &IBorrowRepository_GetBorrowingByID_Call{Call: _e.mock.On("GetBorrowingByID", ctx, id)}
}

func (_c *IBorrowRepository_GetBorrowingByID_Call) Run(run func(ctx context.Context, id int64)) *IBorrowRepository_GetBorrowingByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *IBorrowRepository_GetBorrowingByID_Call) Return(_a0 *entity.Borrowing, _a1 error) *IBorrowRepository_GetBorrowingByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IBorrowRepository_GetBorrowingByID_Call) RunAndReturn(run func(context.Context, int64) (*entity.Borrowing, error)) *IBorrowRepository_GetBorrowingByID_Call {
	_c.Call.Return(run)
	return _c
}

// InsertOrUpdateBorrowing provides a mock function with given fields: ctx, b
func (_m *IBorrowRepository) InsertOrUpdateBorrowing(ctx context.Context, b *entity.Borrowing) error {
	ret := _m.Called(ctx, b)

	if len(ret) == 0 {
		panic("no return value specified for InsertOrUpdateBorrowing")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Borrowing) error); ok {
		r0 = rf(ctx, b)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IBorrowRepository_InsertOrUpdateBorrowing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertOrUpdateBorrowing'
type IBorrowRepository_InsertOrUpdateBorrowing_Call struct {
	*mock.Call
}

// InsertOrUpdateBorrowing is a helper method to define mock.On call
//   - ctx context.Context
//   - b *entity.Borrowing
func (_e *IBorrowRepository_Expecter) InsertOrUpdateBorrowing(ctx interface{}, b interface{}) *IBorrowRepository_InsertOrUpdateBorrowing_Call {
	return &IBorrowRepository_InsertOrUpdateBorrowing_Call{Call: _e.mock.On("InsertOrUpdateBorrowing", ctx, b)}
}

func (_c *IBorrowRepository_InsertOrUpdateBorrowing_Call) Run(run func(ctx context.Context, b *entity.Borrowing)) *IBorrowRepository_InsertOrUpdateBorrowing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Borrowing))
	})
	return _c
}

func (_c *IBorrowRepository_InsertOrUpdateBorrowing_Call) Return(_a0 error) *IBorrowRepository_InsertOrUpdateBorrowing_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IBorrowRepository_InsertOrUpdateBorrowing_Call) RunAndReturn(run func(context.Context, *entity.Borrowing) error) *IBorrowRepository_InsertOrUpdateBorrowing_Call {
	_c.Call.Return(run)
	return _c
}

// IsBookBorrowed provides a mock function with given fields: ctx, userID, bookID
func (_m *IBorrowRepository) IsBookBorrowed(ctx context.Context, userID int64, bookID int64) (bool, error) {
	ret := _m.Called(ctx, userID, bookID)

	if len(ret) == 0 {
		panic("no return value specified for IsBookBorrowed")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) (bool, error)); ok {
		return rf(ctx, userID, bookID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) bool); ok {
		r0 = rf(ctx, userID, bookID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = rf(ctx, userID, bookID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IBorrowRepository_IsBookBorrowed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsBookBorrowed'
type IBorrowRepository_IsBookBorrowed_Call struct {
	*mock.Call
}

// IsBookBorrowed is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - bookID int64
func (_e *IBorrowRepository_Expecter) IsBookBorrowed(ctx interface{}, userID interface{}, bookID interface{}) *IBorrowRepository_IsBookBorrowed_Call {
	return &IBorrowRepository_IsBookBorrowed_Call{Call: _e.mock.On("IsBookBorrowed", ctx, userID, bookID)}
}

func (_c *IBorrowRepository_IsBookBorrowed_Call) Run(run func(ctx context.Context, userID int64, bookID int64)) *IBorrowRepository_IsBookBorrowed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *IBorrowRepository_IsBookBorrowed_Call) Return(_a0 bool, _a1 error) *IBorrowRepository_IsBookBorrowed_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IBorrowRepository_IsBookBorrowed_Call) RunAndReturn(run func(context.Context, int64, int64) (bool, error)) *IBorrowRepository_IsBookBorrowed_Call {
	_c.Call.Return(run)
	return _c
}

// NewIBorrowRepository creates a new instance of IBorrowRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIBorrowRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IBorrowRepository {
	mock := &IBorrowRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
