// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package infrastructure

// Injectors from wire.go:

func InitInfra() (*RedisClient, error) {
	redisClient := NewRedis()
	return redisClient, nil
}
