version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      mysql:
          condition: service_healthy
    environment:
      - PORT=8080
      - DB_DSN=bookuser:bookpass@tcp(mysql:3306)/bookdb?parseTime=true
    command: [ "./main" ]

  mysql:
    image: mysql:8
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bookdb
      MYSQL_USER: bookuser
      MYSQL_PASSWORD: bookpass
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 5

  migrate:
    image: migrate/migrate
    depends_on:
      - mysql
    volumes:
      - ./migrations:/migrations
    command: [
      "-path", "/migrations",
      "-database", "mysql://bookuser:bookpass@tcp(mysql:3306)/bookdb",
      "up"
    ]

volumes:
  db_data:
