// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package book

import (
	"book-lending-api/config"
	"book-lending-api/internal/book/delivery/http"
	"book-lending-api/internal/book/repository"
	"book-lending-api/internal/book/usecase"
	"book-lending-api/pkg/db"
	"book-lending-api/pkg/logger"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitBookHandler() *http.Handler {
	envConfig := ProvideEnvConfig()
	db := ProvideDatabase(envConfig)
	logrusLogger := logger.NewLogger()
	bookRepository := repository.NewBookRepository(db, logrusLogger)
	bookUsecase := usecase.NewBookUseCase(bookRepository, logrusLogger)
	handler := http.NewHandler(bookUsecase, logrusLogger)
	return handler
}

// wire.go:

func ProvideEnvConfig() *config.EnvConfig {
	return config.LoadEnv()
}

func ProvideDatabase(cfg *config.EnvConfig) *gorm.DB {
	return db.InitializeMySQL(cfg)
}
