// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package user

import (
	"book-lending-api/config"
	"book-lending-api/internal/user/delivery/http"
	"book-lending-api/internal/user/repository"
	"book-lending-api/internal/user/usecase"
	"book-lending-api/pkg/authentication"
	"book-lending-api/pkg/db"
	"book-lending-api/pkg/logger"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitUserHandler() *http.Handler {
	envConfig := ProvideEnvConfig()
	db := ProvideDatabase(envConfig)
	logrusLogger := logger.NewLogger()
	userRepository := repository.NewMySQLRepository(db, logrusLogger)
	jwtService := authentication.NewJWTService(envConfig)
	userUsecase := usecase.NewUserUseCase(userRepository, jwtService)
	handler := http.NewHandler(userUsecase, logrusLogger)
	return handler
}

// wire.go:

func ProvideEnvConfig() *config.EnvConfig {
	return config.LoadEnv()
}

func ProvideDatabase(cfg *config.EnvConfig) *gorm.DB {
	return db.InitializeMySQL(cfg)
}
